// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"

import "jquery"
import "custom/bootstrap"
import "custom/classie-search"
import "custom/creditly"
import "custom/demo1-search"
import "custom/easy-responsive-tabs"
import "custom/imagezoom"
import "custom/jquery-ui"
import "custom/jquery.easing.min"
import "custom/jquery.flexslider"
import "custom/jquery.magnific-popup"
import "custom/minicart"
import "custom/modernizr-2.6.2.min"
import "custom/move-top"
import "custom/owl.carousel"
import "custom/simplyCountdown"
